apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.ui.type }}
  ports:
  - port: 8384
    targetPort: 8384
    protocol: TCP
    name: gui
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
