apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}-sync
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
  {{- with .Values.services.sync.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.sync.type }}
  ports:
  - port: 22000
    targetPort: 22000
    protocol: TCP
    name: file-transfer
  - port: 22000
    targetPort: 22000
    protocol: UDP
    name: file-transfer-quic
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
