apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}-discovery
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
  {{- with .Values.services.discovery.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.discovery.type }}
  ports:
  - port: 21027
    targetPort: 21027
    protocol: UDP
    name: discovery
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
