apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncthing.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 10Gi
